// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/shortener.proto

package shortener

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateShortLinkRequest represents a request to create a single short link
type CreateShortLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkRequest) Reset() {
	*x = CreateShortLinkRequest{}
	mi := &file_proto_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkRequest) ProtoMessage() {}

func (x *CreateShortLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateShortLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortLinkRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

// CreateShortLinkResponse represents the response for creating a short link
type CreateShortLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	IsDuplicate   bool                   `protobuf:"varint,2,opt,name=is_duplicate,json=isDuplicate,proto3" json:"is_duplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkResponse) Reset() {
	*x = CreateShortLinkResponse{}
	mi := &file_proto_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkResponse) ProtoMessage() {}

func (x *CreateShortLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateShortLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortLinkResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *CreateShortLinkResponse) GetIsDuplicate() bool {
	if x != nil {
		return x.IsDuplicate
	}
	return false
}

// OriginalLinkBatch represents a single URL in a batch request
type OriginalLinkBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OriginalLinkBatch) Reset() {
	*x = OriginalLinkBatch{}
	mi := &file_proto_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OriginalLinkBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OriginalLinkBatch) ProtoMessage() {}

func (x *OriginalLinkBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OriginalLinkBatch.ProtoReflect.Descriptor instead.
func (*OriginalLinkBatch) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *OriginalLinkBatch) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *OriginalLinkBatch) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

// CreateShortLinkBatchRequest represents a request to create multiple short links
type CreateShortLinkBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*OriginalLinkBatch   `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkBatchRequest) Reset() {
	*x = CreateShortLinkBatchRequest{}
	mi := &file_proto_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkBatchRequest) ProtoMessage() {}

func (x *CreateShortLinkBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkBatchRequest.ProtoReflect.Descriptor instead.
func (*CreateShortLinkBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShortLinkBatchRequest) GetLinks() []*OriginalLinkBatch {
	if x != nil {
		return x.Links
	}
	return nil
}

// ShortedLinkBatch represents a single shortened URL in a batch response
type ShortedLinkBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortedLinkBatch) Reset() {
	*x = ShortedLinkBatch{}
	mi := &file_proto_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortedLinkBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortedLinkBatch) ProtoMessage() {}

func (x *ShortedLinkBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortedLinkBatch.ProtoReflect.Descriptor instead.
func (*ShortedLinkBatch) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *ShortedLinkBatch) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ShortedLinkBatch) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

// CreateShortLinkBatchResponse represents the response for creating multiple short links
type CreateShortLinkBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*ShortedLinkBatch    `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShortLinkBatchResponse) Reset() {
	*x = CreateShortLinkBatchResponse{}
	mi := &file_proto_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShortLinkBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortLinkBatchResponse) ProtoMessage() {}

func (x *CreateShortLinkBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortLinkBatchResponse.ProtoReflect.Descriptor instead.
func (*CreateShortLinkBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *CreateShortLinkBatchResponse) GetLinks() []*ShortedLinkBatch {
	if x != nil {
		return x.Links
	}
	return nil
}

// GetURLRequest represents a request to get the original URL
type GetURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortId       string                 `protobuf:"bytes,1,opt,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLRequest) Reset() {
	*x = GetURLRequest{}
	mi := &file_proto_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLRequest) ProtoMessage() {}

func (x *GetURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLRequest.ProtoReflect.Descriptor instead.
func (*GetURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *GetURLRequest) GetShortId() string {
	if x != nil {
		return x.ShortId
	}
	return ""
}

// GetURLResponse represents the response containing the original URL
type GetURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,2,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLResponse) Reset() {
	*x = GetURLResponse{}
	mi := &file_proto_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLResponse) ProtoMessage() {}

func (x *GetURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLResponse.ProtoReflect.Descriptor instead.
func (*GetURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *GetURLResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *GetURLResponse) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

// GetAllByUserIDRequest represents a request to get all URLs for a user
type GetAllByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllByUserIDRequest) Reset() {
	*x = GetAllByUserIDRequest{}
	mi := &file_proto_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllByUserIDRequest) ProtoMessage() {}

func (x *GetAllByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetAllByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{8}
}

// UserURL represents a single URL belonging to a user
type UserURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserURL) Reset() {
	*x = UserURL{}
	mi := &file_proto_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserURL) ProtoMessage() {}

func (x *UserURL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserURL.ProtoReflect.Descriptor instead.
func (*UserURL) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{9}
}

func (x *UserURL) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *UserURL) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

// GetAllByUserIDResponse represents the response containing all user URLs
type GetAllByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*UserURL             `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllByUserIDResponse) Reset() {
	*x = GetAllByUserIDResponse{}
	mi := &file_proto_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllByUserIDResponse) ProtoMessage() {}

func (x *GetAllByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllByUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetAllByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllByUserIDResponse) GetUrls() []*UserURL {
	if x != nil {
		return x.Urls
	}
	return nil
}

// DeleteBatchRequest represents a request to delete multiple URLs
type DeleteBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrls     []string               `protobuf:"bytes,1,rep,name=short_urls,json=shortUrls,proto3" json:"short_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBatchRequest) Reset() {
	*x = DeleteBatchRequest{}
	mi := &file_proto_shortener_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBatchRequest) ProtoMessage() {}

func (x *DeleteBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBatchRequest.ProtoReflect.Descriptor instead.
func (*DeleteBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteBatchRequest) GetShortUrls() []string {
	if x != nil {
		return x.ShortUrls
	}
	return nil
}

// DeleteBatchResponse represents the response for deleting URLs
type DeleteBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBatchResponse) Reset() {
	*x = DeleteBatchResponse{}
	mi := &file_proto_shortener_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBatchResponse) ProtoMessage() {}

func (x *DeleteBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBatchResponse.ProtoReflect.Descriptor instead.
func (*DeleteBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetStatsRequest represents a request to get service statistics
type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_shortener_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{13}
}

// GetStatsResponse represents the response containing service statistics
type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          int32                  `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users         int32                  `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_shortener_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{14}
}

func (x *GetStatsResponse) GetUrls() int32 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *GetStatsResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

// PingRequest represents a health check request
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_shortener_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{15}
}

// PingResponse represents a health check response
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_shortener_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shortener_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_shortener_proto_rawDescGZIP(), []int{16}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_shortener_proto protoreflect.FileDescriptor

const file_proto_shortener_proto_rawDesc = "" +
	"\n" +
	"\x15proto/shortener.proto\x12\tshortener\";\n" +
	"\x16CreateShortLinkRequest\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"Y\n" +
	"\x17CreateShortLinkResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\fis_duplicate\x18\x02 \x01(\bR\visDuplicate\"]\n" +
	"\x11OriginalLinkBatch\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"Q\n" +
	"\x1bCreateShortLinkBatchRequest\x122\n" +
	"\x05links\x18\x01 \x03(\v2\x1c.shortener.OriginalLinkBatchR\x05links\"V\n" +
	"\x10ShortedLinkBatch\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"Q\n" +
	"\x1cCreateShortLinkBatchResponse\x121\n" +
	"\x05links\x18\x01 \x03(\v2\x1b.shortener.ShortedLinkBatchR\x05links\"*\n" +
	"\rGetURLRequest\x12\x19\n" +
	"\bshort_id\x18\x01 \x01(\tR\ashortId\"R\n" +
	"\x0eGetURLResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x02 \x01(\bR\tisDeleted\"\x17\n" +
	"\x15GetAllByUserIDRequest\"I\n" +
	"\aUserURL\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"@\n" +
	"\x16GetAllByUserIDResponse\x12&\n" +
	"\x04urls\x18\x01 \x03(\v2\x12.shortener.UserURLR\x04urls\"3\n" +
	"\x12DeleteBatchRequest\x12\x1d\n" +
	"\n" +
	"short_urls\x18\x01 \x03(\tR\tshortUrls\"/\n" +
	"\x13DeleteBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x11\n" +
	"\x0fGetStatsRequest\"<\n" +
	"\x10GetStatsResponse\x12\x12\n" +
	"\x04urls\x18\x01 \x01(\x05R\x04urls\x12\x14\n" +
	"\x05users\x18\x02 \x01(\x05R\x05users\"\r\n" +
	"\vPingRequest\"&\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xb7\x04\n" +
	"\x10ShortenerService\x12X\n" +
	"\x0fCreateShortLink\x12!.shortener.CreateShortLinkRequest\x1a\".shortener.CreateShortLinkResponse\x12g\n" +
	"\x14CreateShortLinkBatch\x12&.shortener.CreateShortLinkBatchRequest\x1a'.shortener.CreateShortLinkBatchResponse\x12=\n" +
	"\x06GetURL\x12\x18.shortener.GetURLRequest\x1a\x19.shortener.GetURLResponse\x12U\n" +
	"\x0eGetAllByUserID\x12 .shortener.GetAllByUserIDRequest\x1a!.shortener.GetAllByUserIDResponse\x12L\n" +
	"\vDeleteBatch\x12\x1d.shortener.DeleteBatchRequest\x1a\x1e.shortener.DeleteBatchResponse\x12C\n" +
	"\bGetStats\x12\x1a.shortener.GetStatsRequest\x1a\x1b.shortener.GetStatsResponse\x127\n" +
	"\x04Ping\x12\x16.shortener.PingRequest\x1a\x17.shortener.PingResponseB3Z1github.com/VladSnap/shortener/proto/gen/shortenerb\x06proto3"

var (
	file_proto_shortener_proto_rawDescOnce sync.Once
	file_proto_shortener_proto_rawDescData []byte
)

func file_proto_shortener_proto_rawDescGZIP() []byte {
	file_proto_shortener_proto_rawDescOnce.Do(func() {
		file_proto_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shortener_proto_rawDesc), len(file_proto_shortener_proto_rawDesc)))
	})
	return file_proto_shortener_proto_rawDescData
}

var file_proto_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_shortener_proto_goTypes = []any{
	(*CreateShortLinkRequest)(nil),       // 0: shortener.CreateShortLinkRequest
	(*CreateShortLinkResponse)(nil),      // 1: shortener.CreateShortLinkResponse
	(*OriginalLinkBatch)(nil),            // 2: shortener.OriginalLinkBatch
	(*CreateShortLinkBatchRequest)(nil),  // 3: shortener.CreateShortLinkBatchRequest
	(*ShortedLinkBatch)(nil),             // 4: shortener.ShortedLinkBatch
	(*CreateShortLinkBatchResponse)(nil), // 5: shortener.CreateShortLinkBatchResponse
	(*GetURLRequest)(nil),                // 6: shortener.GetURLRequest
	(*GetURLResponse)(nil),               // 7: shortener.GetURLResponse
	(*GetAllByUserIDRequest)(nil),        // 8: shortener.GetAllByUserIDRequest
	(*UserURL)(nil),                      // 9: shortener.UserURL
	(*GetAllByUserIDResponse)(nil),       // 10: shortener.GetAllByUserIDResponse
	(*DeleteBatchRequest)(nil),           // 11: shortener.DeleteBatchRequest
	(*DeleteBatchResponse)(nil),          // 12: shortener.DeleteBatchResponse
	(*GetStatsRequest)(nil),              // 13: shortener.GetStatsRequest
	(*GetStatsResponse)(nil),             // 14: shortener.GetStatsResponse
	(*PingRequest)(nil),                  // 15: shortener.PingRequest
	(*PingResponse)(nil),                 // 16: shortener.PingResponse
}
var file_proto_shortener_proto_depIdxs = []int32{
	2,  // 0: shortener.CreateShortLinkBatchRequest.links:type_name -> shortener.OriginalLinkBatch
	4,  // 1: shortener.CreateShortLinkBatchResponse.links:type_name -> shortener.ShortedLinkBatch
	9,  // 2: shortener.GetAllByUserIDResponse.urls:type_name -> shortener.UserURL
	0,  // 3: shortener.ShortenerService.CreateShortLink:input_type -> shortener.CreateShortLinkRequest
	3,  // 4: shortener.ShortenerService.CreateShortLinkBatch:input_type -> shortener.CreateShortLinkBatchRequest
	6,  // 5: shortener.ShortenerService.GetURL:input_type -> shortener.GetURLRequest
	8,  // 6: shortener.ShortenerService.GetAllByUserID:input_type -> shortener.GetAllByUserIDRequest
	11, // 7: shortener.ShortenerService.DeleteBatch:input_type -> shortener.DeleteBatchRequest
	13, // 8: shortener.ShortenerService.GetStats:input_type -> shortener.GetStatsRequest
	15, // 9: shortener.ShortenerService.Ping:input_type -> shortener.PingRequest
	1,  // 10: shortener.ShortenerService.CreateShortLink:output_type -> shortener.CreateShortLinkResponse
	5,  // 11: shortener.ShortenerService.CreateShortLinkBatch:output_type -> shortener.CreateShortLinkBatchResponse
	7,  // 12: shortener.ShortenerService.GetURL:output_type -> shortener.GetURLResponse
	10, // 13: shortener.ShortenerService.GetAllByUserID:output_type -> shortener.GetAllByUserIDResponse
	12, // 14: shortener.ShortenerService.DeleteBatch:output_type -> shortener.DeleteBatchResponse
	14, // 15: shortener.ShortenerService.GetStats:output_type -> shortener.GetStatsResponse
	16, // 16: shortener.ShortenerService.Ping:output_type -> shortener.PingResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_shortener_proto_init() }
func file_proto_shortener_proto_init() {
	if File_proto_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shortener_proto_rawDesc), len(file_proto_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shortener_proto_goTypes,
		DependencyIndexes: file_proto_shortener_proto_depIdxs,
		MessageInfos:      file_proto_shortener_proto_msgTypes,
	}.Build()
	File_proto_shortener_proto = out.File
	file_proto_shortener_proto_goTypes = nil
	file_proto_shortener_proto_depIdxs = nil
}
