// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/VladSnap/shortener/internal/handlers (interfaces: ShorterService)

// Package handlers is a generated GoMock package.
package handlers

import (
	reflect "reflect"

	services "github.com/VladSnap/shortener/internal/services"
	gomock "github.com/golang/mock/gomock"
)

// MockShorterService is a mock of ShorterService interface.
type MockShorterService struct {
	ctrl     *gomock.Controller
	recorder *MockShorterServiceMockRecorder
}

// MockShorterServiceMockRecorder is the mock recorder for MockShorterService.
type MockShorterServiceMockRecorder struct {
	mock *MockShorterService
}

// NewMockShorterService creates a new mock instance.
func NewMockShorterService(ctrl *gomock.Controller) *MockShorterService {
	mock := &MockShorterService{ctrl: ctrl}
	mock.recorder = &MockShorterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShorterService) EXPECT() *MockShorterServiceMockRecorder {
	return m.recorder
}

// CreateShortLink mocks base method.
func (m *MockShorterService) CreateShortLink(arg0 string) (*services.ShortedLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortLink", arg0)
	ret0, _ := ret[0].(*services.ShortedLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShortLink indicates an expected call of CreateShortLink.
func (mr *MockShorterServiceMockRecorder) CreateShortLink(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortLink", reflect.TypeOf((*MockShorterService)(nil).CreateShortLink), arg0)
}

// CreateShortLinkBatch mocks base method.
func (m *MockShorterService) CreateShortLinkBatch(arg0 []*services.OriginalLink) ([]*services.ShortedLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortLinkBatch", arg0)
	ret0, _ := ret[0].([]*services.ShortedLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShortLinkBatch indicates an expected call of CreateShortLinkBatch.
func (mr *MockShorterServiceMockRecorder) CreateShortLinkBatch(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortLinkBatch", reflect.TypeOf((*MockShorterService)(nil).CreateShortLinkBatch), arg0)
}

// GetURL mocks base method.
func (m *MockShorterService) GetURL(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockShorterServiceMockRecorder) GetURL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockShorterService)(nil).GetURL), arg0)
}
